### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by JonZeolla** [SeisoLLC/zeek-kafka#10]
# Summary of the issue
Releases should:
- Be simple and automated
- Use GitHub's release mechanism
- Include a changelog
- Ensure `zkg.meta` points to that release's version, allowing us to change our `main`'s `zkg.meta` to indicate `main` as the `version`.

Consider backfilling releases for 0.1, 0.2, and 0.3.

**Comment by JonZeolla** [comment]
@ottobackwards any additional acceptance criteria you'd like to see with automated releases?

**Comment by ottobackwards** [comment]
Can we define what a release entails?

**Comment by JonZeolla** [comment]
I intended the first comment to have everything.  Are you thinking process as well?

**Comment by JonZeolla** [comment]
https://github.com/SeisoLLC/zeek-kafka/pull/26
