### ISSUE TITLE
Installing zeek-Kafka error

### ISSUE THREAD

**Issue by cybersecurity99** [SeisoLLC/zeek-kafka#34]
# Summary of the issue
I am trying to install zeek-kafka
But facing error

## Expected behavior
...
I expect it to get installed 
## Steps to reproduce
...
$ curl -L https://github.com/edenhill/librdkafka/archive/v1.4.2.tar.gz | tar xvz
$ cd librdkafka-1.4.2/
$ ./configure --enable-sasl
$ make
$ sudo make install

/opt/zeek/bin/zkg install seisollc/zeek-kafka
*Where applicable, consider providing a patch that uses the [end to end testing environment](https://github.com/seisollc/zeek-kafka/blob/main/docker/run_end_to_end.sh).*

## Logs, errors, etc.
...
`root@CT:/opt/zeek/bin# ./zkg install seisollc/zeek-kafka
The following packages will be INSTALLED:
  zeek/seisollc/zeek-kafka (v1.0.0)

Verify the following REQUIRED external dependencies:
(Ensure their installation on all relevant systems before proceeding):
  from zeek/seisollc/zeek-kafka (v1.0.0):
    librdkafka ~1.4.2-RC1

Proceed? [Y/n] Y
zeek/seisollc/zeek-kafka asks for LIBRDKAFKA_ROOT (Path to librdkafka installation tree root) ? [/usr/local]
Saved answers to config file: /opt/zeek/etc/zkg/config
Running unit tests for "zeek/seisollc/zeek-kafka"
error: "zeek/seisollc/zeek-kafka" tests failed, inspect contents of /opt/zeek/var/lib/zkg/testing/zeek-kafka for details, especially any "zkg.test_command.{stderr,stdout}" files within /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka
Proceed to install anyway? [N/y] y
Installing "zeek/seisollc/zeek-kafka"...................................................
Installed "zeek/seisollc/zeek-kafka" (v1.0.0)
Loaded "zeek/seisollc/zeek-kafka"
root@CT:/opt/zeek/bin# ./zeek -N Seiso::Kafka
error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/lib/zeek/plugins/packages/zeek-kafka//lib/SEISO-KAFKA.linux-x86_64.so: /usr/local/lib/librdkafka++.so.1: undefined symbol: rd_kafka_commit_transaction
fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors
root@CT:/opt/zeek/bin# ^C
`

zkg.test_command.stderr

kafka.l2s-l2e-no-overlap ... failed
  % 'zeek ../../../scripts/Seiso/Kafka/ /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/tests/.tmp/kafka.l2s-l2e-no-overlap/l2s-l2e-no-overlap.zeek > output' failed unexpectedly (exit code 1)
  % cat .stderr
  error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/build//lib/SEISO-KAFKA.linux-x86_64.so: /usr/local/lib/librdkafka++.so.1: undefined symbol: rd_kafka_commit_transaction
  fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors

kafka.l2s-set-l2e-set ... failed
  % 'zeek ../../../scripts/Seiso/Kafka/ /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/tests/.tmp/kafka.l2s-set-l2e-set/l2s-set-l2e-set.zeek > output' failed unexpectedly (exit code 1)
  % cat .stderr
  error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/build//lib/SEISO-KAFKA.linux-x86_64.so: /usr/local/lib/librdkafka++.so.1: undefined symbol: rd_kafka_commit_transaction
  fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors

kafka.l2s-set-l2e-unset ... failed
  % 'zeek ../../../scripts/Seiso/Kafka/ /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/tests/.tmp/kafka.l2s-set-l2e-unset/l2s-set-l2e-unset.zeek > output' failed unexpectedly (exit code 1)
  % cat .stderr
  error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/var/lib/zkg/testing/zeek-kafka/clones/zeek-kafka/build//lib/SEISO-KAFKA.linux-x86_64.so: /usr/local/lib/librdkafka++.so.1: undefined symbol: rd_kafka_commit_transaction
  fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors

## Your environment
* Version of Zeek  : 4.0.5
* Version or commit hash of the zeek-kafka package : latest
* Operating System and version Ubuntu 18.04

**Comment by cybersecurity99** [comment]
> I cannot reproduce this in our docker environment ( which was already using 1.4.2 but is using ubuntu 20x ) I have updated the zkg meta requirement to drop the rc.

How I download your latest commit ,
this command will fetch original i guess curl -L https://github.com/edenhill/librdkafka/archive/v1.4.2.tar.gz | tar xvz
Can you give me a git clone command so that i get that

**Comment by ottobackwards** [comment]
It was just merged to main

**Comment by cybersecurity99** [comment]
> It was just merged to main

I went with Manual Installation , it was installed but still local.zeek can't find package
