### ISSUE TITLE
Support for zeek 4.2

### ISSUE THREAD

**Issue by ottobackwards** [SeisoLLC/zeek-kafka#45]
# Summary of the issue
Before 5.0 releases there should be support for the last 4.x feature release

## Expected behavior
...

## Steps to reproduce
...

*Where applicable, consider providing a patch that uses the [end to end testing environment](https://github.com/seisollc/zeek-kafka/blob/main/docker/run_end_to_end.sh).*

## Logs, errors, etc.
...

## Your environment
* Version of Zeek
* Version or commit hash of the zeek-kafka package
* Operating System and version

**Comment by JonZeolla** [comment]
Added in 009c6cdf1e69fd7cbe0038e42a84dcc48ac72fce
