### ISSUE TITLE
Fix README instructions to not include sasl

### ISSUE THREAD

**Issue by JonZeolla** [SeisoLLC/zeek-kafka#50]
# Summary of the issue
[Currently](https://github.com/SeisoLLC/zeek-kafka/blob/03f0a34bbe97096f59a1de53e393a3385e956f9a/README.md#zkg-installation) we specify to run `./configure --enable-sasl`, but many environments (and most of our users) do not have kerberized kafka clusters.  We should default to the most typical setup instructions, but keep the note about enabling sasl.

**Comment by derekseisollc** [comment]
This has been resolved with PR [54](https://github.com/SeisoLLC/zeek-kafka/pull/54)
