### ISSUE TITLE
I had installed zeek-kafka zeek-kafka-1.1.0,but I got  (dynamic, version 0.3.0) when I show version

### ISSUE THREAD

**Issue by micoder122** [SeisoLLC/zeek-kafka#74]
My server version is centos 7,please help me.
How can I change plugin version 1.1.0 to zeek zeek version 5.0.10

### x86_64

[ 37%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/src/Plugin.cc.o
[ 43%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/src/TaggedJSON.cc.o
[ 50%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/kafka.bif.cc.o
[ 56%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/kafka.bif.init.cc.o
[ 62%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/kafka.bif.register.cc.o
[ 68%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/events.bif.cc.o
[ 75%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/events.bif.init.cc.o
[ 81%] Building CXX object CMakeFiles/SEISO-KAFKA.linux-x86_64.dir/events.bif.register.cc.o
[ 87%] Linking CXX shared module lib/SEISO-KAFKA.linux-x86_64.so
make[3]: 离开目录“/zeek-kafka-1.1.0/build”
[ 93%] Built target SEISO-KAFKA.linux-x86_64
make[3]: 进入目录“/zeek-kafka-1.1.0/build”
Scanning dependencies of target dist
make[3]: 离开目录“/zeek-kafka-1.1.0/build”
make[3]: 进入目录“/zeek-kafka-1.1.0/build”
[100%] Building binary plugin package: SEISO_KAFKA.tgz
make[3]: 离开目录“/zeek-kafka-1.1.0/build”
[100%] Built target dist
make[2]: 离开目录“/zeek-kafka-1.1.0/build”
Install the project...
-- Install configuration: "RelWithDebInfo"
make[1]: 离开目录“/zeek-kafka-1.1.0/build”
[1]+  退出 2                make
[root@localhost zeek-kafka-1.1.0]# ldconfig

[root@localhost zeek-kafka-1.1.0]# zeek -N Seiso::Kafka
Seiso::Kafka - Writes logs to Kafka (dynamic, version 0.3.0)

**Comment by ottobackwards** [comment]
This will be fixed *after* 1.2.0 releases

**Comment by ottobackwards** [comment]
pr #76
