### ISSUE TITLE
zeek-kafka installation causes zeek startup failure

### ISSUE THREAD

**Issue by puquanyang0326** [SeisoLLC/zeek-kafka#81]
Hi, I installed zeek-6.0.2 via rpm package on a centos8 machine, and then proceeded to install librdkafka and zeek-kafka, which were successful, but reported errors when running zeek. Without installing zeek-kafka, zeek is working fine.The same operation is possible to install and use zeek-kafka on the previous centos7 machines.I hope you can give some help, thank you！

[ZeekControl] > deploy
checking configurations ...
zeek scripts failed.
error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /opt/zeek/lib/zeek/plugins/SEISO_KAFKA//lib/SEISO-KAFKA.linux-x86_64.so: /opt/zeek/lib/zeek/plugins/SEISO_KAFKA//lib/SEISO-KAFKA.linux-x86_64.so: undefined symbol: _ZN4zeek6plugin6Plugin12HookLoadFileENS1_8LoadTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_
fatal error in /opt/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors

**Comment by ottobackwards** [comment]
how did you install the plugin? what version of the plugin?
